version: "3"
services:
  cloudflare_workerd_test:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
      args:
        WORKDIR: /project
    volumes:
      - ..:/project
    image: cloudflare_workerd_test-image
    container_name: cloudflare_workerd_test-container
    tty: true
    env_file: ../.env # shellスクリプト内でも環境変数として使用するため
